version: '3.7'

services:
  php:
    build: .
    volumes:
      - ./:/app
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=smart-media-test

